theme: jekyll-theme-minimal
title: Seven Seas Of Something
description: SEPR Project W.I.P
baseurl: /All-Hands-On-Deck
logo: https://raw.githubusercontent.com/7SeasOfSomething/UnnamedGame/master/docs/images/Logo.png
#show_downloads: true #This lets you download the entire current repo, maybe it's not exactly what we're looking for right now.
